# Generated by Django 4.1 on 2025-07-17 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_plano_options_alter_plano_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_barbearia', models.CharField(max_length=200, verbose_name='Nome da Barbearia')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço Completo')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Barbearia',
                'verbose_name_plural': 'Barbearias',
                'db_table': 'crm_barbearia',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('aceite_termos', models.BooleanField(default=False, verbose_name='Aceitou Termos de Uso')),
                ('receber_notificacoes', models.BooleanField(default=False, verbose_name='Deseja receber notificações')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'crm_usuario',
            },
        ),
        migrations.AlterModelTable(
            name='plano',
            table='crm_plano',
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pagamento Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='pendente', max_length=20, verbose_name='Status do Pagamento')),
                ('status_usuario', models.CharField(choices=[('padrao', 'Usuário Padrão'), ('premium', 'Usuário Premium'), ('admin', 'Administrador')], default='padrao', max_length=20, verbose_name='Status do Usuário')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_expiracao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('id_transacao_pagamento', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID da Transação de Pagamento')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='crm.barbearia', verbose_name='Barbearia Associada')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='crm.plano', verbose_name='Plano Contratado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='crm.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'db_table': 'crm_assinatura',
            },
        ),
    ]
