# Generated by Django 4.1 on 2025-07-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_barbearia_usuario_alter_plano_table_assinatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='status_pagamento',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='status_assinatura',
            field=models.CharField(
                choices=[
                    ('trialing', 'Em Período de Teste'),
                    ('active', 'Ativa'),
                    ('past_due', 'Vencida'),
                    ('canceled', 'Cancelada'),
                    ('unpaid', 'Não Paga'),
                ],
                default='trialing',
                max_length=20,
                verbose_name='Status da Assinatura',
            ),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='stripe_subscription_id',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name='ID da Assinatura no Stripe',
            ),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='trial_end',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Fim do Período de Teste'
            ),
        ),
        migrations.AddField(
            model_name='plano',
            name='interval',
            field=models.CharField(
                blank=True,
                choices=[
                    ('day', 'Diário'),
                    ('week', 'Semanal'),
                    ('month', 'Mensal'),
                    ('year', 'Anual'),
                ],
                max_length=20,
                null=True,
                verbose_name='Intervalo de Cobrança',
            ),
        ),
        migrations.AddField(
            model_name='plano',
            name='stripe_price_id',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name='ID do Preço no Stripe',
            ),
        ),
        migrations.AddField(
            model_name='plano',
            name='trial_period_days',
            field=models.IntegerField(
                default=0,
                help_text='Número de dias de teste gratuito para este plano de assinatura.',
                verbose_name='Dias de Teste Gratuito',
            ),
        ),
        migrations.AddField(
            model_name='usuario',
            name='stripe_customer_id',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name='ID do Cliente no Stripe',
            ),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='data_expiracao',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Data de Término do Período',
            ),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='data_inicio',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Data de Início do Período'
            ),
        ),
    ]
