# Generated by Django 4.1 on 2025-08-04 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='status_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='Se True, o acesso será revogado apenas ao final do período pago.', verbose_name='Cancelar no final do período'),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='instance_url',
            field=models.URLField(blank=True, help_text='URL única da instância do cliente no sistema de templates (ex: https://minhabarbearia.templates.com.br)', max_length=255, null=True, verbose_name='URL da Instância do Template App'),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minhas_barbearias_criadas', to='crm.usuario', verbose_name='Usuário Responsável (CRM)'),
        ),
    ]
